project:
  type: website
  output-dir: C:\Users\skopitz.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "Sarah Kopitz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

